name: Setup Jenkins
description: Set up Jenkins container
author: SnowCait
branding:
  icon: circle
  color: blue
inputs:
  jenkins_home:
    description: |
      Jenkins home path which will be mounted to /var/jenkins_home.
      Set '' if you don't want to mount.
    required: false
    default: ${{ runner.temp }}/jenkins_home
  jenkins_image_tag:
    description: Jenkins image tag
    required: false
    default: lts-jdk11
runs:
  using: composite
  steps:
    - run: docker version
      shell: bash
    - run: docker compose version
      shell: bash
    - name: Set env
      run: |
        set -x
        if [[ "$JENKINS_HOME" == "" ]]; then
          echo "JENKINS_HOME=" >> $GITHUB_ENV
        else
          echo "JENKINS_HOME=$(realpath $JENKINS_HOME)" >> $GITHUB_ENV
        fi
        echo "JENKINS_URL=http://localhost:8080" >> $GITHUB_ENV
      shell: bash
      env:
        JENKINS_HOME: ${{ inputs.jenkins_home }}
    - name: COMPOSE_FILE
      run: |
        set -x
        ACTION_PATH=$(realpath $GITHUB_ACTION_PATH)
        if [[ "$JENKINS_HOME" == "" ]]; then
          echo "COMPOSE_FILE=$ACTION_PATH/compose.yaml" >> $GITHUB_ENV
        else
          echo "COMPOSE_FILE=$ACTION_PATH/compose.yaml:$ACTION_PATH/compose.mount.yaml" >> $GITHUB_ENV
        fi
      shell: bash
    - run: |
        mkdir -p $JENKINS_HOME
        sudo chown -R 1000:1000 $JENKINS_HOME
      shell: bash
      if: env.JENKINS_HOME != ''
    - name: Install JCasC plugin
      run: |
        if [ -f "$JENKINS_HOME/jenkins.yaml" ]; then
          echo 'configuration-as-code' >> $GITHUB_ACTION_PATH/plugins.txt
        fi
      shell: bash
    - run: docker compose config
      shell: bash
      env:
        JENKINS_IMAGE_TAG: ${{ inputs.jenkins_image_tag }}
    - run: docker compose up -d --wait
      shell: bash
      env:
        JENKINS_IMAGE_TAG: ${{ inputs.jenkins_image_tag }}
    - run: echo "JENKINS_VERSION=$(docker compose exec jenkins printenv JENKINS_VERSION)" >> $GITHUB_ENV
      shell: bash
