services:
  jenkins:
    build:
      context: .
      args:
        version: ${JENKINS_VERSION}
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ${JENKINS_HOME}:/var/jenkins_home
    privileged: true
    environment:
      - JAVA_OPTS="-Djenkins.install.runSetupWizard=false"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
