services:
  jenkins:
    build:
      context: .
      args:
        tag: ${JENKINS_IMAGE_TAG}
    ports:
      - 8080:8080
      - 50000:50000
    environment:
      - JAVA_OPTS="-Djenkins.install.runSetupWizard=false"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
