name: Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test-mount:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04, ubuntu-18.04 ]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          jenkins_home: test-resources/jenkins_home
      - run: curl http://localhost:8080/

      # Environment variables
      - run: test -n "$JENKINS_HOME"
      - run: test -n "$JENKINS_VERSION"

      # Remote Access API
      # https://www.jenkins.io/doc/book/using/remote-access-api/
      - run: |
          crumb=$(curl -sS -c cookie http://localhost:8080/crumbIssuer/api/json)
          echo "CRUMB_HEADER=$(echo $crumb | jq -r '.crumbRequestField'): $(echo $crumb | jq -r '.crumb')" >> $GITHUB_ENV
      - run: test $(curl -sS -X POST -H "${CRUMB_HEADER}" -b cookie http://localhost:8080/api/json | jq '.jobs | length') -eq 2
      - run: curl -sS -X POST -H "${CRUMB_HEADER}" -b cookie http://localhost:8080/job/job-1/build

      # Jenkins CLI
      # https://www.jenkins.io/doc/book/managing/cli/
      - run: wget http://localhost:8080/jnlpJars/jenkins-cli.jar
      - run: java -jar jenkins-cli.jar -s http://localhost:8080/ -webSocket help
      - run: java -jar jenkins-cli.jar -s http://localhost:8080/ -webSocket list-plugins
      - run: java -jar jenkins-cli.jar -s http://localhost:8080/ -webSocket list-jobs
      - run: java -jar jenkins-cli.jar -s http://localhost:8080/ -webSocket build job-1 -f -v
      - run: java -jar jenkins-cli.jar -s http://localhost:8080/ -webSocket build job-2 -f -v -p param_1=p1

  test-no-mount:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04, ubuntu-18.04 ]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
      - uses: ./
      - run: curl http://localhost:8080/

      # Remote Access API
      # https://www.jenkins.io/doc/book/using/remote-access-api/
      - run: |
          crumb=$(curl -sS -c cookie http://localhost:8080/crumbIssuer/api/json)
          echo "CRUMB_HEADER=$(echo $crumb | jq -r '.crumbRequestField'): $(echo $crumb | jq -r '.crumb')" >> $GITHUB_ENV
      - run: test $(curl -sS -X POST -H "${CRUMB_HEADER}" -b cookie http://localhost:8080/api/json | jq '.jobs | length') -eq 0

      # Jenkins CLI
      # https://www.jenkins.io/doc/book/managing/cli/
      - run: wget http://localhost:8080/jnlpJars/jenkins-cli.jar
      - run: java -jar jenkins-cli.jar -s http://localhost:8080/ -webSocket help
      - run: java -jar jenkins-cli.jar -s http://localhost:8080/ -webSocket list-plugins
      - run: java -jar jenkins-cli.jar -s http://localhost:8080/ -webSocket list-jobs
      - run: java -jar jenkins-cli.jar -s http://localhost:8080/ -webSocket create-job job-1 < test-resources/jenkins_home/jobs/job-1/config.xml
      - run: java -jar jenkins-cli.jar -s http://localhost:8080/ -webSocket create-job job-2 < test-resources/jenkins_home/jobs/job-2/config.xml
      - run: java -jar jenkins-cli.jar -s http://localhost:8080/ -webSocket list-jobs
      - run: java -jar jenkins-cli.jar -s http://localhost:8080/ -webSocket build job-1 -f -v
      - run: java -jar jenkins-cli.jar -s http://localhost:8080/ -webSocket build job-2 -f -v -p param_1=p1

  test-passing:
    needs: [ test-mount, test-no-mount ]
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - run: echo "All tests have passed."
