name: Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test-mount:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04, ubuntu-18.04 ]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          jenkins_home: test-resources/jenkins_home
      - run: curl http://localhost:8080/
      - run: |
          crumb=$(curl -sS -c cookie http://localhost:8080/crumbIssuer/api/json)
          echo "CRUMB_HEADER=$(echo $crumb | jq -r '.crumbRequestField'): $(echo $crumb | jq -r '.crumb')" >> $GITHUB_ENV
      - run: test $(curl -sS -X POST -H "${CRUMB_HEADER}" -b cookie http://localhost:8080/api/json | jq '.jobs | length') -eq 1
      - run: curl -sS -X POST -H "${CRUMB_HEADER}" -b cookie http://localhost:8080/job/job-1/build

  test-no-mount:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04, ubuntu-18.04 ]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
      - uses: ./
      - run: curl http://localhost:8080/
      - run: |
          crumb=$(curl -sS -c cookie http://localhost:8080/crumbIssuer/api/json)
          echo "CRUMB_HEADER=$(echo $crumb | jq -r '.crumbRequestField'): $(echo $crumb | jq -r '.crumb')" >> $GITHUB_ENV
      - run: test $(curl -sS -X POST -H "${CRUMB_HEADER}" -b cookie http://localhost:8080/api/json | jq '.jobs | length') -eq 0
